### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by Leosly7663** [Leosly7663/Weather-Data-Analysis#6]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.[8](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:9)/x64/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/http/client.py", line 12[9](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:10)8, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/http/client.py", line [10](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:11)52, in _send_output
    self.send(msg)
  File "/opt/hostedtoolcache/Python/3.[11](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:12).8/x64/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/http/client.py", line 1470, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/ssl.py", line [13](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:14)82, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Weather-Data-Analysis/Weather-Data-Analysis/autoScrape.py", line 110, in <module>
    scrapeWeather(cityLink,mainForecast,futureForecast)
  File "/home/runner/work/Weather-Data-Analysis/Weather-Data-Analysis/autoScrape.py", line 59, in scrapeWeather
    weatherDoc = urlopen(weatherReq).read()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 2[16](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:17), in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 5[19](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:20), in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 1[35](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8036560476/job/21950412088#step:5:36)1, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
Error: Process completed with exit code 1.

**Comment by Leosly7663** [comment]
[Errno 104] the connection was reset by peer
Guessing this is either an intermediary host by URL request making the URL request and that agent disconnected, 
Or the page in request returned 104 so www.weather.gc.ca was the one to break connection
