### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Leosly7663** [Leosly7663/Weather-Data-Analysis#7]
Traceback (most recent call last):
  File "/home/runner/work/Weather-Data-Analysis/Weather-Data-Analysis/autoScrape.py", line 110, in <module>
    scrapeWeather(cityLink,mainForecast,futureForecast)
  File "/home/runner/work/Weather-Data-Analysis/Weather-Data-Analysis/autoScrape.py", line 59, in scrapeWeather
    weatherDoc = urlopen(weatherReq).read()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.[8](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8040762754/job/21959238308#step:5:9)/x64/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 4[9](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8040762754/job/21959238308#step:5:10)6, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.[11](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8040762754/job/21959238308#step:5:12).8/x64/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 5[25](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8040762754/job/21959238308#step:5:26), in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 6[34](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8040762754/job/21959238308#step:5:35), in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/urllib/request.py", line 6[43](https://github.com/Leosly7663/Weather-Data-Analysis/actions/runs/8040762754/job/21959238308#step:5:44), in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Proxy Error
Error: Process completed with exit code 1.

**Comment by Leosly7663** [comment]
might just set up a function to rerun the scrape on network errors, most times a proxy error or connection refusal can be fixed with just a quick refresh/ request
